export default  {
  generate:(state,action)=>(
    {
      type:"map.generate"
    }
  ),
  spawn:(state,action)=>{
    state.get().map.enemy.set(action.entityid,action.data)
  },
  save:(state,action)=>{
    state.get().dungeon.mapset.set(action.level,
          state.get().map);
  },
  load:(state,action)=>(
    {
      type:"map.load",
      map:state.get().dungeon.mapset[action.level||
          state.get().dungeon.level]
    }
  ),
  ascend:(state,action)=>(
    state.get().dungeon.set('level',
          state.get().dungeon.level-1)
  ),
  descend:(state,action)=>(
    state.get().dungeon.set('level',
          state.get().dungeon.level+1)
  )
}
